# Generated by Django 2.2.24 on 2022-02-15 12:23

from django.db import migrations
from ..models import Flat


def fill_new_building_field(apps, schema_editor):
    flats = Flat.objects.all()
    for flat in flats:
        flat.new_building = flat.construction_year >= 2015
        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_field)
    ]
