# Generated by Django 2.2.24 on 2022-02-15 13:13

from django.db import migrations
from ..models import Flat, Owner


def create_owners(apps, schema_editor):
    flats = Flat.objects.all()
    for flat in flats:
        Owner.objects.get_or_create(owner=flat.owner,
                                    owners_phonenumber=flat.owners_phonenumber,
                                    owner_pure_phone=flat.owner_pure_phone,
                                    )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20220215_1607'),
    ]

    operations = [
        migrations.RunPython(create_owners)
    ]
