# Generated by Django 2.2.24 on 2022-02-15 13:46

from django.db import migrations
from ..models import Flat, Owner


def give_flats(apps, schema_editor):
    flats = Flat.objects.all()
    owners = Owner.objects.all()
    for flat in flats:
        this_owner = owners.get(owner=flat.owner, owners_phonenumber=flat.owners_phonenumber)
        this_owner.flats_owned.add(flat)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_auto_20220215_1646'),
    ]

    operations = [
        migrations.RunPython(give_flats)
    ]
